### ISSUE TITLE
ssd1306_i2c not found even when ls lists it 

### ISSUE THREAD

**Issue by ripjohnbrown1859** [milkv-duo/duo-examples#12]
[root@milkv-duo]~# ls
helloworld  ssd1306_i2c
[root@milkv-duo]~# ./ssd1306_i2c
-sh: ./ssd1306_i2c: not found
i dont know why it is saying it is not there when it clearly is there in the directory.

**Comment by carbonfix** [comment]
fixed. please use the latest code.
