### ISSUE TITLE
PWM not working properly

### ISSUE THREAD

**Issue by vickash** [milkv-duo/duo-examples#18]
I'm using a Duo 256M, with the 1.1.3 image, the latest versions of the duo-sdk repo, and this repo. Testing with included PWM example.

If I use PWM on any pin **except** GPIO2, there's no output. Even with GPIO2, the first run fails, with these errors:
```
ERROR: The Sophgo SG2002 failed to write to /sys/class/pwm/pwmchip4/pwmchip3/enable for PWM (Invalid argument)
ERROR: The Sophgo SG2002 failed to write to /sys/class/pwm/pwmchip4/pwmchip3/polarity for PWM (Invalid argument)
```
I can run it again for GPIO2, which will not show the error, and give the correct output.

For all other GPIOs (with a PWM on the pinout diagram), subsequent runs give no errors, but also no output.

**Comment by Rjgawuie** [comment]
please check https://github.com/milkv-duo/duo-examples/pull/17/commits/c47f990bad8dbafd2ac162f3bef9ac8ce59c3d9c

**Comment by vickash** [comment]
That gets rid of the error messages, and it works on first run now, but I still have no output on any of the other pins. Only GPIO2.

**Comment by Rjgawuie** [comment]
I confirm the pwm is working correct. Are you sure the pinmux is multiplexing the correct function?
please following this link: https://milkv.io/docs/duo/application-development/pinmux

**Comment by vickash** [comment]
Oh. Somehow I jumped from the example straight to the PWM section of the WiringX page, and missed that entirely. Yep, it works fine. Sorry for the confusion.
