### ISSUE TITLE
Can't compile on an ARM-based computer (aarch64)

### ISSUE THREAD

**Issue by Plaque-fcc** [milkv-duo/duo-examples#5]
Hello, I tried compiling examples with the SDK which `envsetup.sh` downloads, and no luck — because it's made for x86_64.

Where can I get a version for ARM machines, or maybe I can get somewhere your SDK source and compile it to work on ARM?

Thanks in advance.

**Comment by yue-xiaomin** [comment]
https://community.milkv.io/t/m1-arm64-debian11-uos-v20/255
https://community.milkv.io/t/duo-arm64/1184

**Comment by carbonfix** [comment]
Sorry, currently the official toolchain can only provide x86_64 version. You need to try the toolchain for other architecture hosts yourself.

**Comment by Plaque-fcc** [comment]
> https://community.milkv.io/t/m1-arm64-debian11-uos-v20/255 https://community.milkv.io/t/duo-arm64/1184

Doesn't work, @yue-xiaomin
