### ISSUE TITLE
dht22 is reading nothing...

### ISSUE THREAD

**Issue by protektwar** [milkv-duo/duo-examples#7]
Hello,

I have compiled dht22 example on the duo board where I'm running Ubuntu
It can't read the values...

![image](https://github.com/milkv-duo/duo-examples/assets/45262264/d3ad09bc-1edf-423f-b3b9-ed950ae4ffd5)

**Comment by pauloantuns** [comment]
Hello @protekwar,

I made few changes on the DHT example to support the DHT11 sensor.  While using the example, i had a lot errors.

![image](https://github.com/milkv-duo/duo-examples/assets/81638459/70ed203f-b9d4-4fc1-8c7f-47222bdd8c30)

Try with the modifications that i made.
https://github.com/pauloantuns/duo-examples/blob/main/dht22/dht.c

**Comment by protektwar** [comment]
My problem was that the board and the sensors have not been grounded together :(. Now the code is working.
